
<div class="container text-center mt-2">
    <div class="row">
        <div class="col-md-7">
            <div class="table-wrapper-scroll-y my-custom-scrollbar">
                <div class="table-responsive">

                    <table class="table table-striped table-dark w-100">
                        <thead>
                        <tr>
                            <th scope="col">Prénom</th>
                            <th scope="col">Nom</th>

                            <th scope="col">Niveau</th>
                            <th scope="col" style="width: 300px;">Roles</th>
                            <th scope="col"><i class="fa-solid fa-trash"></i></th>

                        </tr>
                        </thead>
                        <tbody>
                        <?php use WebAppSeller\Models\Developpeur;

                        foreach ($this->view->collaborateurs as $collaborateur) { ?>
                            <tr>
                                <td><?= $collaborateur->getPrenom() ?></td>
                                <td><?= $collaborateur->getNom() ?></td>

                                <td><?= $collaborateur->translateLevel() ?></td>




                                <td>
                                    <?php if ($collaborateur->isDeveloppeur()) {
                                        $developpeur = Developpeur::findFirst([
                                            'conditions' => 'id_collaborateur = :id:',
                                            'bind' => ['id' => $collaborateur->getId()]
                                        ]);
                                        echo 'Developpeur '; echo $developpeur->translateCompetence(); } ?>

                                    <?php if ($collaborateur->isDeveloppeur() && $collaborateur->isChefDeProjet()) {echo "<br>"; } ?>
                                    <?php if ($collaborateur->isChefDeProjet()) { echo 'Chef de Projet'; } ?>
                                </td>
                                <td class="p-2">
                                    <form action="<?= $this->url->get('WebAppSeller/collaborateur/delete') ?>" method="post" style="display: inline-block;">
                                        <input type="hidden" name="del" value="<?= $collaborateur->getId() ?>">
                                        <button type="submit" class="btn btn-light"><i class="fa-solid fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                 </div>
            </div>
        </div>
        <div class="col-md-5">
            <h3 class="text-center">Ajouter un Collaborateur</h3>
            <div class="container text-center mt-2 w-75">

                <form action="<?= $this->url->get('WebAppSeller/collaborateur/save') ?>" method="post">

                    <div class="form-group ">
                        <label for="prenom_collaborateur">Prénom :</label>
                        <input type="text" name="prenom_collaborateur" placeholder="Exemple : Anselm" class="form-control" id="prenom_collaborateur" required>
                    </div>
                    <div class="form-group mt-2">
                        <label for="nom_collaborateur">Nom :</label>
                        <input type="text" name="nom_collaborateur" placeholder="Exemple : Trinh" class="form-control" id="nom_collaborateur" required>
                    </div>
                    <div class="form-group mt-2 mb-2">
                        <label for="prime_embauche">Prime d'embauche :</label><!---->
                        <input  name="prime_embauche" placeholder="Exemple : 50000" class="form-control" id="prime_embauche"required>
                    </div
                    <div class="form-group">
                        <label for="niveau_competence">Niveau de Compétence :</label>
                        <select name="niveau_competence" class="form-control" id="niveau_competence">
                            <option value="1">Stagiaire</option>
                            <option value="2">Junior</option>
                            <option value="3">Senior</option>
                        </select>
                    </div>

                    <div class="form-group mt-2">

                        <h6>Rôle(s) du collaborateur</h6>
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                            <label class="btn  btn-outline-primary ">
                                <input type="checkbox" name="roles[]" value="developpeur"  id="is_developpeur" autocomplete="off" > Developpeur
                            </label>
                            <label class="btn btn-outline-primary">
                                <input type="checkbox" name="roles[]" value="chef_de_projet" id="is_chef_de_projet" autocomplete="off"> Chef de Projet
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 "">
                            <div id="indice_production_field">


                                <div class="form-group mt-2">

                                    <label for="indice_production">Indice de production :</label>
                                    <input type="number" name="indice_production" placeholder="Exemple : 50%" class="form-control" id="indice_production" min ="1" max="100" required>

                                </div>
                                <div class="form-group">
                                    <label for="competence">Compétence :</label>
                                    <select name="competence" class="form-control" id="competence">
                                        <option value="1">BDD</option>
                                        <option value="2">Back End</option>
                                        <option value="3">Front End</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="col-6">
                            <div class="form-group mt-2 " id="boost_production_field">

                                <label for="boost_production">Boost de production :</label>
                                <input type="number" name="boost_production" placeholder="Exemple : 30%" class="form-control" id="boost_production" min ="1" max="100" required>

                            </div>
                        </div>
                    </div>


                    <button type="submit" class="btn btn-primary m-3">Ajouter</button>
                </form>
                <br>


            </div>
            <div class="btn-group justify-content-center mb-5 mt-2">
                <form action="/WebAppSeller/" >
                    <button type="submit" class="btn btn-outline-warning m-1">
                       <i class="fas fa-arrow-left"></i>  Etape précédente
                    </button>
                </form>
                <form action="/WebAppSeller/composition_equipe" class="m-1">
                    <button type="submit" class="btn btn-outline-warning">
                        Prochaine étape <i class="fas fa-arrow-right"></i>
                    </button>
                </form>
            </div>
        </div>

    </div>
</div>



<script>

    function gestionRoles() {
        let isDeveloppeur = document.getElementById('is_developpeur').checked;
        let isChefDeProjet = document.getElementById('is_chef_de_projet').checked;
        // Afficher ou cacher le champ d'indice de production en fonction de la case Developpeur
        var indiceProductionField = document.getElementById('indice_production_field');
        indiceProductionField.style.display = isDeveloppeur ? 'block' : 'none';
        // Afficher ou cacher le champ de compétence en fonction de la case Developpeur
        let competenceField = document.getElementById('competence');
        competenceField.style.display = isDeveloppeur ? 'block' : 'none';
        // Rendre le champ requis uniquement s'il est affiché
        indiceProductionField.querySelector('input').required = isDeveloppeur;
        // Afficher ou cacher le champ de boost de production en fonction de la case Chef de Projet
        let boostProductionField = document.getElementById('boost_production_field');
        boostProductionField.style.display = isChefDeProjet ? 'block' : 'none';
        // Rendre le champ requis uniquement s'il est affiché
        boostProductionField.querySelector('input').required = isChefDeProjet;
    }
    // Attacher la fonction à l'événement de changement des cases à cocher
    document.getElementById('is_developpeur').addEventListener('change', gestionRoles);
    document.getElementById('is_chef_de_projet').addEventListener('change', gestionRoles);
    // Appeler la fonction une fois au chargement de la page pour définir l'état initial
    gestionRoles();

</script>

