<div class="container text-center mt-2">
    <table class="table table-striped table-dark">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Libelle</th>

        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->view->applications as $application) { ?>
            <tr>
                <td><?= $application->getId() ?></td>
                <td><?= $application->getLibelle() ?></td>


            </tr>
        <?php } ?>
        </tbody>
    </table>

</div>