
<div class="container text-center mt-2">
    <table class="table table-striped table-dark">
        <thead>
        <tr>
            <th scope="col">Application</th>
            <th scope="col">Chef de Projet</th>
            <th scope="col">Prix</th>



        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->view->projets as $projet) { ?>
            <tr>
                <td><?= $projet->getApplication()->getLibelle() ?></td>

                <td><?= $projet->getChefDeProjet()->getCollaborateur()->getPrenom() . " " .$projet->getChefDeProjet()->getCollaborateur()->getNom() ?></td>
                <td><?= $projet->getPrix() ?></td>

            </tr>
        <?php } ?>
        </tbody>
    </table>

</div>