<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Phalcon PHP Framework</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" integrity="sha512-t4GWSVZO1eC8BM339Xd7Uphw5s17a86tIZIj8qRxhnKub6WoyhnrxeCIMeAqBPgdZGlCcG2PrZjMc+Wr78+5Xg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    <style>
        nav .navbar-nav li a {
            color: white !important;
        }
        nav .navbar-nav li a:hover {
            color: lightgrey !important;
        }
        .navbar-nav > .active > a {
            color: red !important;
        }
    </style>
</head>
<body style="background-color: lightgrey">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown" style="flex-direction: column;">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/WebAppSeller/developpeur">Developpeurs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/WebAppSeller/chef_de_projet">Chef de Projet</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/WebAppSeller/application">Application</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/WebAppSeller/collaborateur">Collaborateur</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/WebAppSeller/equipe">Equipes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/WebAppSeller/composition_equipe">Compositions</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/WebAppSeller/client">Clients</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/WebAppSeller/projet">Projets</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?php echo $this->getContent(); ?>
</div>
<!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>
