<div class="row">
    <!--Chef de Projet-->
    <div class="col-md-6">
        <div class="container text-center mt-2">
            <table class="table table-striped table-dark">
                <thead>
                <tr>
                    <th scope="col">ID</th>

                    <th scope="col">Boost de production</th>
                    <th scope="col">Prenom</th>
                    <th scope="col">Nom</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->view->chefdeprojets as $chefdeprojet) { ?>
                    <tr>
                        <td><?= $chefdeprojet->getId() ?></td>


                        <td><?= $chefdeprojet->getBoostProduction() ?></td>
                        <td><?= $chefdeprojet->getCollaborateur()->getPrenom() ?></td>
                        <td><?= $chefdeprojet->getCollaborateur()->getNom() ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

        </div>
    </div>
    <!-- Développeurs -->
    <div class="col-md-6">
        <div class="container text-center mt-2">
            <table class="table table-striped table-dark">
                <thead>
                <tr>
                    <th scope="col">Competence</th>
                    <th scope="col">Indice de production</th>
                    <th scope="col">Prenom</th>
                    <th scope="col">Nom</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->view->developpeurs as $developpeur) { ?>
                    <tr>
                        <td><?= $developpeur->getCompetence() ?></td>

                        <td><?= $developpeur->getIndiceProduction() ?></td>
                        <td><?= $developpeur->getCollaborateur()->getPrenom() ?></td>
                        <td><?= $developpeur->getCollaborateur()->getNom() ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

        </div>

    </div>
</div>