<div class="container text-center mt-2">
    <table class="table table-striped table-dark">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nom de l'équipe</th>
            <th scope="col">Chef d'équipe</th>


        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->view->equipes as $equipe) { ?>

            <tr>
                <td><?= $equipe->getId() ?></td>
                <td><?= $equipe->getLibelle() ?></td>
                <td><?= $equipe->getChefDeProjet()->getCollaborateur()->getPrenom() ?></td>

            </tr>

        <?php } ?>
        </tbody>
    </table>

</div>

<!-- Button trigger modal -->
<div class="d-flex justify-content-center">
    <button type="button" class="btn btn-warning " data-bs-toggle="modal" data-bs-target="#exampleModal">
        Rajouter une équipe
    </button>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Création d'équipe</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="/create-team" method="POST"> <!-- Add the action and method attributes -->
                    <div class="form-group">
                        <label for="team">Nom de l'équipe : </label>
                        <input type="text" class="form-control" id="team" name="team" required>
                    </div>
                    <div class="form-group">
                        <label for="chef_projet">Nom du chef de projet : </label>
                        <input type="text" class="form-control" id="chef_projet" name="chef_projet">
                    </div>
                </form>
            </div>


            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <button type="button" class="btn btn-success">Créer</button>
            </div>
        </div>
    </div>
</div>
