<!-- views/equipe/new.phtml -->

<div class="container">
    <h2>Création d'équipe</h2>
    <form action="/equipe/create" method="post">
        <div class="form-group">
            <label for="team">Nom de l'équipe :</label>
            <input type="text" class="form-control" id="team" name="team" required>
        </div>
        <div class="form-group">
            <label for="chef_projet">Nom du chef de projet :</label>
            <input type="text" class="form-control" id="chef_projet" name="chef_projet">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Créer</button>
            <a href="/equipe" class="btn btn-secondary">Annuler</a>
        </div>
    </form>
</div>
