
<div class="container text-center mt-2">
    <table class="table table-striped table-dark">
        <thead>
        <tr>
            <th scope="col">Competence</th>
            <th scope="col">Indice de production</th>
            <th scope="col">Prenom</th>
            <th scope="col">Nom</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->view->developpeurs as $developpeur) { ?>
            <tr>
                <td><?= $developpeur->getCompetence() ?></td>

                <td><?= $developpeur->getIndiceProduction() ?></td>
                <td><?= $developpeur->getCollaborateur()->getPrenom() ?></td>
                <td><?= $developpeur->getCollaborateur()->getNom() ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

</div>