

<div class="row mt-5">

    <div class="col-md-6">


        <div class="container mt-2">
            <div class="row ">
                <?php foreach ($this->view->groupedCompositions as $teamName => $compositions) { ?>
                    <?php if (!empty($compositions)) { ?>


                        <div class="col-md-6 mb-4 ">
                            <div class="card bg-dark h-100 shadow ">

                                <div class="row">
                                    <div class="text-center col-6">
                                        <a href="<?= $this->url->get('WebAppSeller/projet') ?>" class="btn btn-info w-100 d-block">Selectionner</a>
                                    </div>
                                    
                                    <div class="text-center col-6">
                                        <form action="<?= $this->url->get('WebAppSeller/composition_equipe/delete') ?>" method="post">
                                            <input type="hidden" name="id" value="<?= $compositions[0]->getEquipe()->getId()?>">
                                            <button type="submit" class="btn btn-danger w-100 d-block"><i class="fa-solid fa-trash"></i></button>
                                        </form>
                                    </div>
                                </div>



                                
                                <div class="card-body text-white text-center">
                                    <h1 class="card-title pb-3 border-bottom"><?= $teamName ?></h1>

                                    <h4 class="card-subtitle pb-3 pt-3 border-bottom">Chef de projet : 
                                        <?= $compositions[0]->getEquipe()->getChefDeProjet()->getCollaborateur()->getPrenom() ?>
                                    </h4>

                                    <h3 class="card-subtitle mb-3 pt-3">Développeurs:</h3>
                                    <ul class="list-group">
                                        <?php foreach ($compositions as $composition) { ?>
                                            <li class="list-group-item">
                                                <?= $composition->getDeveloppeur()->getCollaborateur()->getPrenom() ?>
                                            </li>
                                        <?php } ?>
                                    </ul>
                                </div>



                            </div>
                        </div>
                    <?php } ?>
                <?php } ?>
            </div>
        </div>



    </div>


    <div class="col-md-6">

    <h1 class="text-center "><strong>Composez votre équipe</strong></h1>
    <div class="container text-center mt-2 w-75">
        <form action="<?= $this->url->get('WebAppSeller/composition_equipe/save') ?>" method="post">
            <div class="form-group">
                <h2 for="team_name">Nom de l'équipe</h2>
                <input type="text" class="form-control bg-light" name="team_name" id="team_name" required>
            </div>
    <!--        Chef d'équipe input-->
            <div class="form-group">
                <h3 for="chef">Choisissez votre chef d'équipe</h3>
                <select name="chef" class="form-control bg-light" id="chef">
                    <?php foreach ($this->view->chefdeprojets as $chefdeprojet) { ?>
                        <option value="<?= $chefdeprojet->getId() ?>"><?= $chefdeprojet->getCollaborateur()->getPrenom() ?></option>
                    <?php } ?>
                </select>
            </div>

            <!-- Multiple select for developers -->
            <div class="form-group">
                <h3 for="chef">Choisissez vos membres</h3>
                <select name="developpeur[]" class="form-control bg-light" id="chef" multiple="multiple">
                    <?php foreach ($this->view->developpeurs as $developpeur) { ?>
                        <option value="<?= $developpeur->getId() ?>"><?= $developpeur->getCollaborateur()->getPrenom() ?></option>
                    <?php } ?>
                </select>
            </div>

            <button type="submit" class="btn btn-primary m-3">Valider</button>
        </form>

    </div>
</div>
</div>
