
<h1 class="text-center m-5"><strong>Choisissez une équipe existante ou composez votre équipe</strong></h1>

<div class="container mt-2">
    <div class="row row-card">
        <?php foreach ($this->view->groupedCompositions as $teamName => $compositions) { ?>
            <div class="col-md-3 mb-4 ">
                //Boutons Select et Delete
                <div class="card bg-dark h-100 shadow ">
                    <div class="row">
                        <div class="text-center col-6">
                            <form action="/WebAppSeller/equipe_selectionne" method="post">
                                <input type="hidden" name="equipe_id" value="<?= $compositions[0]->getEquipe()->getId() ?>">
                                <button type="submit" class="btn btn-info w-100 d-block">Select</button>
                            </form>
                        </div>
                        <div class="text-center col-6 ">
                            <form action="<?= $this->url->get('WebAppSeller/composition_equipe/delete') ?>" method="post" ">
                                <input type="hidden" name="id" value="<?= $compositions[0]->getEquipe()->getId()?>">
                                <button type="submit" class="btn btn-danger w-100 d-block"><i class="fa-solid fa-trash"></i></button>
                            </form>
                        </div>
                    </div>

                    <div class="card-body text-white text-center">
                        //Nom de l'équipe
                        <h1 class="card-title pb-3 border-bottom"><?= $teamName ?></h1>
                        //Nom du chef de projet
                        <h4 class="card-subtitle pb-3 pt-3 border-bottom">Chef de projet : <?= $compositions[0]->getEquipe()->getChefDeProjet()->getCollaborateur()->getPrenom() ?></h4>
                        //Liste des développeurs
                        <h3 class="card-subtitle mb-3 pt-3">Développeurs:</h3>
                        <ul class="list-group">
                            <?php foreach ($compositions as $composition) { ?>
                                <li class="list-group-item"><?= $composition->getDeveloppeur()->getCollaborateur()->getPrenom() ?></li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>

</div>

<div class="container text-center mt-2 w-75">
    <form action="<?= $this->url->get('WebAppSeller/composition_equipe/save') ?>" method="post">
        <div class="form-group">
            <h2 for="team_name">Nom de l'équipe</h2>
            <input type="text" class="form-control bg-light" name="team_name" id="team_name" required>
        </div>
<!--        Chef d'équipe input-->
        <div class="form-group">
            <h3 for="chef">Choisissez votre chef d'équipe</h3>
            <select name="chef" class="form-control bg-light" id="chef">
                <?php foreach ($this->view->chefdeprojets as $chefdeprojet) { ?>
                    <option value="<?= $chefdeprojet->getId() ?>"><?= $chefdeprojet->getCollaborateur()->getPrenom() ?></option>
                <?php } ?>
            </select>
        </div>
<!--        Check boxs Développeurs-->
        <div class="form-group mt-3">
            <?php $counter = 0; ?>
            <h2>Choisissez vos membres</h2>
            <div class="row">
                <?php foreach ($this->view->developpeurs as $developpeur) { ?>
                <div class="col-md-3">
                    <div class="form-check ">
                        <input type="checkbox" name="developpeur[]" value="<?= $developpeur->getId() ?>" class="form-check-input" id="dev_<?= $developpeur->getId() ?>">
                        <label class="form-check-label" for="dev_<?= $developpeur->getId() ?>"><?= $developpeur->getCollaborateur()->getPrenom() ?></label>
                    </div>
                </div>
                <?php $counter++;
                if ($counter % 4 === 0) { ?>
            </div><div class="row">
                <?php } ?>
                <?php } ?>
            </div>
        </div>
        <button type="submit" class="btn btn-primary m-3">Valider</button>
    </form>

</div>

